site_name: Note 
site_url: https://note.fredmontet.com/
theme:
    name: material
    features:
        - navigation.tabs
    palette: 
        - scheme: default
          toggle:
            icon: material/toggle-switch-off-outline 
            name: Switch to dark mode
        - scheme: slate 
          toggle:
            icon: material/toggle-switch
            name: Switch to light mode
    font:
        text: Roboto
        code: Roboto Mono
repo_name: fredmontet/note
repo_url: https://github.com/fredmontet/note

